#! /bin/bash

# This batch file and Run-REDUCE-FX.jar must be in the same directory.
# The Java 11 bin directory must be in PATH and the environment
# variable PATH_TO_FX must be set to the JavaFX 11 lib directory.
# Then Run-REDUCE-FX.jar can be run from anywhere by running this batch file.
# Any command-line arguments are passed on to Run-REDUCE-FX.jar.

java -Djdk.gtk.version=2 --module-path "${PATH_TO_FX//\"/}" --add-modules javafx.controls,javafx.fxml,javafx.web -jar $(dirname $0)/Run-REDUCE-FX.jar $*
